# Generated by Django 3.1.2 on 2021-02-27 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150), hello.models.number_only]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='mail',
            field=models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[a-z*$')]),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.friend')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
